<style>
 .alert.alert-warning ,.alert.alert-success {
    width: 48%;
    padding: 20px;
    margin-left: 0;
    /* float: left; */
}

</style>
<?php 
//$status = $this->status;
if($status == 0)
{
	 echo '<div class="alert alert-warning">
		  <strong>Warning!</strong> Error  Delete
		</div>';
}
if($status == 1)
{
	echo '<div class="alert alert-success">
		  <strong>Success!</strong> Delete
		</div>';
}
 
?>